// Code generated by "stringer -type=Nm80211APSec"; DO NOT EDIT.

package gonetworkmanager

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Nm80211APSecNone-0]
	_ = x[Nm80211APSecPairWEP40-1]
	_ = x[Nm80211APSecPairWEP104-2]
	_ = x[Nm80211APSecPairTKIP-4]
	_ = x[Nm80211APSecPairCCMP-8]
	_ = x[Nm80211APSecGroupWEP40-16]
	_ = x[Nm80211APSecGroupWEP104-32]
	_ = x[Nm80211APSecGroupTKIP-64]
	_ = x[Nm80211APSecGroupCCMP-128]
	_ = x[Nm80211APSecKeyMgmtPSK-256]
	_ = x[Nm80211APSecKeyMgmt8021X-512]
	_ = x[Nm80211APSecKeyMgmtSAE-1024]
	_ = x[Nm80211APSecKeyMgmtOWE-2048]
	_ = x[Nm80211APSecKeyMgmtOWETM-4096]
}

const _Nm80211APSec_name = "Nm80211APSecNoneNm80211APSecPairWEP40Nm80211APSecPairWEP104Nm80211APSecPairTKIPNm80211APSecPairCCMPNm80211APSecGroupWEP40Nm80211APSecGroupWEP104Nm80211APSecGroupTKIPNm80211APSecGroupCCMPNm80211APSecKeyMgmtPSKNm80211APSecKeyMgmt8021XNm80211APSecKeyMgmtSAENm80211APSecKeyMgmtOWENm80211APSecKeyMgmtOWETM"

var _Nm80211APSec_map = map[Nm80211APSec]string{
	0:    _Nm80211APSec_name[0:16],
	1:    _Nm80211APSec_name[16:37],
	2:    _Nm80211APSec_name[37:59],
	4:    _Nm80211APSec_name[59:79],
	8:    _Nm80211APSec_name[79:99],
	16:   _Nm80211APSec_name[99:121],
	32:   _Nm80211APSec_name[121:144],
	64:   _Nm80211APSec_name[144:165],
	128:  _Nm80211APSec_name[165:186],
	256:  _Nm80211APSec_name[186:208],
	512:  _Nm80211APSec_name[208:232],
	1024: _Nm80211APSec_name[232:254],
	2048: _Nm80211APSec_name[254:276],
	4096: _Nm80211APSec_name[276:300],
}

func (i Nm80211APSec) String() string {
	if str, ok := _Nm80211APSec_map[i]; ok {
		return str
	}
	return "Nm80211APSec(" + strconv.FormatInt(int64(i), 10) + ")"
}
